### ISSUE TITLE
1 assert fails when running the test on RHEL-7.4

### ISSUE THREAD

**Issue by milosmalik** [fedora-selinux/selinux-policy-macros#1]
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: [   LOG    ] :: Test install twice on a clean system
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

:: [  BEGIN   ] :: Running 'rpm --eval '%selinux_set_booleans -s targeted secure_mode=1 secure_mode_insmod=1' > run_selinux_set_booleans.sh'
:: [   PASS   ] :: Command 'rpm --eval '%selinux_set_booleans -s targeted secure_mode=1 secure_mode_insmod=1' > run_selinux_set_booleans.sh' (Expected 0, got 0)
:: [  BEGIN   ] :: Running 'bash run_selinux_set_booleans.sh'
:: [   PASS   ] :: Command 'bash run_selinux_set_booleans.sh' (Expected 0, got 0)
:: [  BEGIN   ] :: Running 'rpm --eval '%selinux_set_booleans -s targeted secure_mode=1 zabbix_can_network=1' > run_selinux_set_booleans.sh'
:: [   PASS   ] :: Command 'rpm --eval '%selinux_set_booleans -s targeted secure_mode=1 zabbix_can_network=1' > run_selinux_set_booleans.sh' (Expected 0, got 0)
:: [  BEGIN   ] :: Running 'bash run_selinux_set_booleans.sh'
:: [   PASS   ] :: Command 'bash run_selinux_set_booleans.sh' (Expected 0, got 0)
:: [  BEGIN   ] :: Running 'semanage boolean -E > boolean.local'
:: [   PASS   ] :: Command 'semanage boolean -E > boolean.local' (Expected 0, got 0)
:: [   PASS   ] :: File 'boolean.local' should contain 'boolean -m \(-1\|--on\) secure_mode' 
:: [   PASS   ] :: File 'boolean.local' should contain 'boolean -m \(-1\|--on\) secure_mode_insmod' 
:: [   PASS   ] :: File 'boolean.local' should contain 'boolean -m \(-1\|--on\) zabbix_can_network' 
:: [  BEGIN   ] :: Running 'cat /etc/selinux/targeted/rpmbooleans.custom'
boolean -m --off secure_mode
boolean -m --off secure_mode_insmod
boolean -m --on secure_mode
boolean -m --off zabbix_can_network
:: [   PASS   ] :: Command 'cat /etc/selinux/targeted/rpmbooleans.custom' (Expected 0, got 0)
:: [   FAIL   ] :: File '/etc/selinux/targeted/rpmbooleans.custom' should not contain '\(-1\|--on\) secure_mode' 
:: [   PASS   ] :: File '/etc/selinux/targeted/rpmbooleans.custom' should not contain '\(-1\|--on\) secure_mode_insmod' 
:: [   PASS   ] :: File '/etc/selinux/targeted/rpmbooleans.custom' should not contain '\(-1\|--on\) zabbix_can_network'

**Comment by milosmalik** [comment]
Following line was removed intentionally, because it breaks the formatting of comments:
# This file is managed by macros.selinux-policy. Do not edit it manually

**Comment by wrabcak** [comment]
@milosmalik 
Is it still actual? 

Thanks,
Lukas

**Comment by milosmalik** [comment]
Should be fixed now, because following bug is verified:
 * https://bugzilla.redhat.com/show_bug.cgi?id=1518609
This issue took long to fix.

**Comment by wrabcak** [comment]
Thanks.
